# Generated by Django 2.2.20 on 2021-04-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
                ('solarSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.SolarSystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[('mineral', 'Mineral'), ('module', 'Module'), ('rig', 'Rig'), ('salvage', 'Salvage')], max_length=255)),
                ('blueprint', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EveAssets.Blueprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialEfficiency', models.IntegerField(default=0)),
                ('timeEfficiency', models.IntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='EveAssets.Blueprint')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Item')),
            ],
        ),
    ]
