# Generated by Django 2.2.20 on 2021-12-02 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
                ('runOutputCount', models.IntegerField(default=1)),
                ('runCicleTime', models.IntegerField()),
                ('maxProductionLimit', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
                ('type', models.CharField(blank=True, choices=[('component', 'Component'), ('mineral', 'Mineral'), ('module', 'Module'), ('rig', 'Rig'), ('salvage', 'Salvage')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('esiId', models.IntegerField(unique=True)),
                ('solarSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.SolarSystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlueprintInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialEfficiency', models.IntegerField(default=0)),
                ('timeEfficiency', models.IntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='EveAssets.Blueprint')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Item')),
            ],
        ),
        migrations.AddField(
            model_name='blueprint',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Item'),
        ),
    ]
