# Generated by Django 2.2.20 on 2021-04-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EveAssets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('mineral', 'Mineral'), ('module', 'Module'), ('rig', 'Rig'), ('salvage', 'Salvage')], max_length=255, null=True),
        ),
    ]
