# Generated by Django 2.2.20 on 2021-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EveAssets', '0002_auto_20210426_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BPO',
            new_name='BlueprintInstance',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='esiId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
