# Generated by Django 2.2.20 on 2021-08-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EveAssets', '0003_auto_20210529_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='blueprint',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EveAssets.Item'),
            preserve_default=False,
        ),
    ]
