# Generated by Django 2.2.20 on 2021-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EveAssets', '0004_auto_20210816_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='maxProductionLimit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blueprint',
            name='runCicleTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blueprint',
            name='runOutputCount',
            field=models.IntegerField(default=1),
        ),
    ]
